apiVersion: v1
kind: Pod
metadata:
  name: backup-postgres-s3
  namespace: dev
spec:
  serviceAccountName: aws-workload
  containers:
  - name: backup-postgres-s3
    image: amazon/aws-cli:latest
    imagePullPolicy: IfNotPresent
    command: ["sleep", "infinity"]
    env:
      - name: PGHOST
        valueFrom:
          configMapKeyRef:
            name: core
            key: DB_HOST
      - name: DB_DATABASE
        value: keeper
      - name: PGUSER
        value: keeper
      - name: PGPASSWORD
        valueFrom:
          secretKeyRef:
            name: app-db-secret
            key: keeper
      - name: S3_BUCKET_NAME
        value: backup-postgres
      - name: S3_REGION
        value: ap-southeast-1
  nodeSelector:
    node.kubernetes.io/asg-name: shared