apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
        - name: app 
          image: ubuntu
          env:
            - name: SECRET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-user
                  key: backend-username
          volumeMounts:
            - name: ssl
              mountPath: /api/ssl  # path to drop file in container (prefix)
              readOnly: true
            - name: keys
              mountPath: /api/keys
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: ssl
          secret:
            secretName: test-secret # secret in k8s-cluster
            items:
              - key: test-key.pem      # key of secret in k8s-cluster
                path: private-test.pem # path to drop file in container (suffix)
              - key: test-cert.pem
                path: cert-test.pem
            defaultMode: 0o600
        - name: keys
          secret:
            secretName: test-secret
            items:
              - key: master.pem
                path: master.pem
              - key: node.pem
                path: node.pem
            defaultMode: 0o600
