version: '3'
services:
  nginx-lb:
    container_name: nginx-lb
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx-lb/nginx.conf:/etc/nginx/nginx.conf
  web1:
    container_name: web1
    image: httpd:alpine
    ports:
      - "9000:80"
    volumes:
      - ./web1/index.html:/usr/local/apache2/htdocs/index.html
  web2:
    container_name: web2
    image: httpd:alpine
    ports:
      - "9001:80"
    volumes:
      - ./web2/index.html:/usr/local/apache2/htdocs/index.html
    
    