apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:7.7
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1"
          env:
          - name: PGADMIN_DEFAULT_EMAIL
            value: DEFAULT_LOGIN_EMAIL
          - name: PGADMIN_DEFAULT_PASSWORD
            value: DEFAULT_LOGIN_PASSWORD
          - name: PGADMIN_CONFIG_CONFIG_DATABASE_CONNECTION_POOL_SIZE
            value: "1"
          - name: PGADMIN_CONFIG_CONFIG_DATABASE_CONNECTION_MAX_OVERFLOW
            value: "1"
          - name: PGADMIN_CONFIG_MAX_SESSION_IDLE_TIME 
            value: "30" # minutes
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          volumeMounts:
          - name: pgadmin-config
            mountPath: /pgadmin4/servers.json
            subPath: servers.json
            readOnly: true
      volumes:
        - name: pgadmin-config
          configMap:
            name: pgadmin-config