apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: nginx
      app.kubernetes.io/name: {{ .Release.Name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: nginx
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      containers:
      - name: nginx
        image: {{ .Values.image }}
        ports:
        - containerPort: 80
      {{- with .Values.tolerations }}
      tolerations:
      {{- range . }}
      - key: {{ .key | default "" }}
        operator: {{ .operator | default "Equal" }}
        value: {{ .value | default "" }}
        effect: {{ .effect | default "NoSchedule" }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
