apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
  namespace: {{ .Values.infra.namespace }}
  annotations: 
    eks.amazonaws.com/role-arn: {{ .Values.config.gitSyncS3.awsRoleArn }}