GRANT ALL PRIVILEGES ON DATABASE "DB_NAME" to "USER_NAME";
GRANT ALL ON SCHEMA public TO "USER_NAME";
GRANT ALL ON ALL TABLES IN SCHEMA public TO "USER_NAME";


GRANT "USER_NAME" to "postgres";
GRANT ALL PRIVILEGES ON DATABASE "DB_NAME" to "postgres";
GRANT ALL ON SCHEMA public TO "postgres";
GRANT ALL ON ALL TABLES IN SCHEMA public TO "postgres";