apiVersion: apps/v1
kind: Deployment
metadata:
  name: psqlcli
  labels:
    app: psqlcli
spec:
  selector:
    matchLabels:
      app: psqlcli
  replicas: 1
  template:
    metadata:
      labels:
        app: psqlcli
    spec:
      containers:
      - name: psqlcli
        image: postgres:16.2-alpine3.19
        imagePullPolicy: Always
        resources:
          requests:
            cpu: {{ default "100m" .Values.config.resource.requests.cpu | quote }}
            memory: {{ default "200Mi" .Values.config.resource.requests.memory | quote }}
          limits:
            cpu: {{ default "100m" .Values.config.resource.limits.cpu | quote }}
            memory: {{ default "200Mi" .Values.config.resource.limits.memory | quote }}
        env:
          {{- range $key, $value := .Values.config.env }}
          - name: {{ $key }}
            value: {{ $value }}
          {{- end }}
