version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/server.crt:/etc/nginx/server.crt
      - ./nginx/server.key:/etc/nginx/server.key
  web1:
    container_name: web1
    image: httpd:alpine
    ports:
      - "9000:80"
    volumes:
      - ./web1/index.html:/usr/local/apache2/htdocs/index.html
  web2:
    container_name: web2
    image: httpd:alpine
    ports:
      - "9001:80"
    volumes:
      - ./web2/index.html:/usr/local/apache2/htdocs/index.html
    
    