apiVersion: apps/v1
kind: Deployment
metadata:
  name: utils-cli
  labels:
    app: utils-cli
spec:
  selector:
    matchLabels:
      app: utils-cli
  replicas: 1
  template:
    metadata:
      labels:
        app: utils-cli
    spec:
      # serviceAccountName: xxxx
      containers:
        - name: utils-cli
          image: arunvelsriram/utils
          imagePullPolicy: Always
          command: ["/bin/bash", "-c", "--"]
          args:
            - "while true; do sleep 30; done;"
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      # nodeSelector:
      #   xxxx: ""
      # tolerations:
      #   - key: ""
      #     operator: "Equal"
      #     value: ""
      #     effect: "NoSchedule"
