version: '3'
services:
  client-1:
    container_name: client-1
    image: ubuntu:latest
    networks:
      network1:
        ipv4_address: 203.0.113.3
    volumes:
      - ./hosts:/etc/hosts
    # tty: true
    command: >
      bash -c "apt update && 
      apt install -y nano && 
      apt install -y curl && 
      apt install -y iputils-ping &&
      tail -f /dev/null"
  
  nginx-lb:
    container_name: nginx-lb
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx-lb/nginx.conf:/etc/nginx/nginx.conf
    networks:
      network1:
        ipv4_address: 203.0.113.2
      network2:
        ipv4_address: 192.168.0.2

  web1:
    container_name: web1
    image: httpd:alpine
    ports:
      - "9000:80"
    volumes:
      - ./web1/index.html:/usr/local/apache2/htdocs/index.html
    networks:
      network2:
        ipv4_address: 192.168.0.3
  
  web2:
    container_name: web2
    image: httpd:alpine
    ports:
      - "9001:80"
    volumes:
      - ./web2/index.html:/usr/local/apache2/htdocs/index.html
    networks:
      network2:
        ipv4_address: 192.168.0.4

networks:
  network1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 203.0.113.0/24

  network2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24