apiVersion: v1
kind: ConfigMap
metadata:
  name: pghero
data:
  pghero.yml: |-
    databases:
      ANYNAME_1:
        url: postgres://USERNAME:PASSWORD@ENDPOINT:5432/DATABASE_A
      ANYNAME_2:
        url: postgres://USERNAME:PASSWORD@ENDPOINT:5432/DATABASE_B
      ANYNAME_3:
        url: postgres://USERNAME:PASSWORD@ENDPOINT:5432/DATABASE_C

    # Minimum time for long running queries
    # long_running_query_sec: 60

    # Minimum average time for slow queries
    # slow_query_ms: 20

    # Minimum calls for slow queries
    # slow_query_calls: 100

    # Minimum connections for high connections warning
    # total_connections_threshold: 500

    # Explain functionality
    # explain: true / false / analyze

    # Statement timeout for explain
    explain_timeout_sec: 60

    # Visualize URL for explain
    # visualize_url: https://...

    # Time zone
    # time_zone: "Pacific Time (US & Canada)"