name: Bin cache

on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BIN_INSTALLER_FILE_PATH: ${{ github.workspace }}/bin_installer.sh
      BIN_DIR_PATH: /usr/local/bin
    steps:
      - name: Checkout
        uses: actions/checkout@4

      - name: Require binary libraries
        run: |
          echo "#!/bin/sh" >> ${{ env.BIN_INSTALLER_FILE_PATH }}
          echo "curl -L ./trivy.tar.gz https://github.com/aquasecurity/trivy/releases/download/v0.54.1/trivy_0.54.1_Linux-64bit.tar.gz | tar xz -C ${{ env.BIN_DIR_PATH }}" >> ${{ env.BIN_INSTALLER_FILE_PATH }}
          chmod +x ${{ env.BIN_INSTALLER_FILE_PATH }}   
      
      - name: Debug hashFiles
        run: |
          ls -l $(dirname ${{ env.BIN_INSTALLER_FILE_PATH }})
          echo "Cache key: ${{ runner.os }}-bash-${{ hashFiles(env.BIN_INSTALLER_FILE_PATH) }}"        

      - uses: actions/cache@v3
        id: bin-cache
        with:
          path: |
            ${{ env.BIN_DIR_PATH }}/trivy
          key: ${{ runner.os }}-bash-${{ hashFiles(env.BIN_INSTALLER_FILE_PATH) }}

      - name: Install Dependencies
        if: steps.bin-cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install -y curl
          ${{ env.BIN_INSTALLER_FILE_PATH }}