- name: Connections
  hosts: databases
  remote_user: root

  tasks:
  - name: Ensure connections
    ansible.builtin.ping:



- name: Update mongodb servers
  hosts: databases
  remote_user: root

  tasks:
  - name: Ensure that mongodb server is installed
    ansible.builtin.apt:
      name: postgresql
      state: latest

  - name: Ensure that mongodb is started
    ansible.builtin.service:
      name: postgresql
      state: started