# helm upgrade --install -f ~/Github/eks/helm-values/values-nginx.yaml nginx bitnami/nginx --version 15.0.1

ingress:
  enabled: true
  hostname: nginx.arpo.website
  ingressClassName: nginx

service:
  type: ClusterIP
