# helm install jenkins -f values-jenkins.yaml bitnami/jenkins --version 12.2.1
ingress:
  ## @param ingress.enabled Enable ingress record generation for Jenkins
  ##
  enabled: true
  ## @param ingress.pathType Ingress path type
  ##
  pathType: ImplementationSpecific
  ## @param ingress.apiVersion Force Ingress API version (automatically detected if not set)
  ##
  apiVersion: ""
  ## @param ingress.hostname Default host for the ingress record
  ##
  hostname: jenkins.arpo.website
  ingressClassName: nginx