name: Install terraform
description: terraform installation with cache from binary file

inputs:
  version:
    description: terraform version
    required: false
    default: 1.9.8
  binary-location:
    description: path of binary file to install such as "/usr/local/bin"
    required: false
    default: /usr/local/bin

runs:
  using: composite
  steps:
    - name: Cache files
      uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
      id: cache
      with:
        path: |
          ${{ inputs.binary-location }}/terraform
        key: ${{ runner.os }}-bash-terraform-v${{ inputs.version }}

    - name: Download & Install
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo apt update && sudo apt install -y gnupg software-properties-common
        wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt update && sudo apt install terraform=${{ inputs.version }}-1
        sudo mv /usr/bin/terraform ${{ inputs.binary-location }}
        terraform -v
