apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}-cronjob
  namespace: {{ .Values.k8s.namespace }}
spec:
  schedule: {{ .Values.config.cron_time }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: restart-container
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - |
              kubectl rollout restart deployment/{{ .Values.config.deployment_target_name }} -n {{ .Values.k8s.namespace }}
          nodeSelector:
            node.kubernetes.io/asg-name: {{ .Values.k8s.asg_name }}
          serviceAccountName: {{ .Chart.Name }}-sa